main: net.servokio.customJaLm.Main
name: CustomJaLm
version: 0.0.1
description: 'Просто плагин.'
author: "D.Y."
website: http://servokio.ru
api-version: "1.13"
commands:
  cjmreload:
    description: Reload plugin config
    usage: /cjmreload
    permission: cjmreload